let kendaraan = [

"Toyota Corolla",
"Volkswagen Golf",
  "Ford F-Series",
  "Honda Civic",
  "Chevrolet Silverado",
  "Toyota Camry",
  "Ram Pickup",
  "Honda Accord",
  "Nissan Rogue",
  "Chevrolet Equinox",
  "Toyota RAV4",
  "Ford Escape",
  "Chevrolet Malibu",
  "Hyundai Elantra",
  "Nissan Altima",
  "Ford Explorer",
  "Jeep Grand Cherokee",
  "Toyota Highlander",
  "Subaru Outback",
  "Honda Pilot",
  "Mazda CX-5",
  "Hyundai Santa Fe",
  "Ford Edge",
  "Kia Sportage",
  "Jeep Wrangler",
  "Toyota Tacoma",
  "Honda CR-V",
  "Ford Mustang",
  "Chevrolet Camaro",
  "Dodge Challenger",
  "Tesla Model 3",
  "Tesla Model S",
  "Tesla Model X",
  "Tesla Model Y",
  "BMW 3 Series",
  "BMW 5 Series",
  "Mercedes-Benz C-Class",
  "Mercedes-Benz E-Class",
  "Audi A4",
  "Audi A6",
  "Lexus RX",
  "Lexus ES",
  "Toyota Land Cruiser",
  "Nissan Patrol",
  "Range Rover",
  "Porsche 911",
  "Ferrari 488",
  "Lamborghini Huracán",
  "McLaren 720S",
  "Bugatti Chiron",
  "Rolls-Royce Phantom",
  "Bentley Continental GT",


    ///pindah model///


"Honda CB750",
"Harley-Davidson Sportster",
    "Yamaha YZF-R1",
    "Kawasaki Ninja ZX-10R",
    "Ducati Panigale V4",
    "BMW S1000RR",
    "Triumph Bonneville",
    "Suzuki Hayabusa",
    "KTM 1290 Super Duke R",
    "MV Agusta F4",
    "Aprilia RSV4",
    "Indian Scout",
    "Royal Enfield Bullet",
    "Moto Guzzi V7",
    "Ducati Monster",
    "Honda Gold Wing",
    "Harley-Davidson Fat Boy",
    "Yamaha MT-09",
    "Kawasaki Z900",
    "BMW R1250GS",
    "Triumph Tiger 800",
    "Suzuki GSX-R1000",
    "KTM 390 Duke",
    "MV Agusta Brutale",
    "Aprilia Tuono",
    "Indian Chief",
    "Royal Enfield Classic",
    "Moto Guzzi V85 TT",
    "Ducati Diavel",
    "Honda Africa Twin",
    "Harley-Davidson Road Glide",
    "Yamaha Tracer 900",
    "Kawasaki Vulcan",
    "BMW F900R",
    "Triumph Speed Triple",
    "Suzuki V-Strom 650",
    "KTM Adventure 790",
    "MV Agusta Dragster",
    "Aprilia Caponord",
    "Indian Chieftain",
    "Royal Enfield Himalayan",
    "Moto Guzzi California",


    ///pindah model///


"Boeing 747",
"Airbus A380",
    "Boeing 737",
    "Airbus A320",
    "Boeing 787 Dreamliner",
    "Airbus A350",
    "Boeing 777",
    "Airbus A330",
    "Boeing 767",
    "Boeing 757",
    "Airbus A340",
    "Embraer E-Jet",
    "Bombardier CRJ",
    "McDonnell Douglas MD-80",
    "Lockheed C-130 Hercules",
    "Cessna 172 Skyhawk",
    "Piper PA-28 Cherokee",
    "Gulfstream G650",
    "Dassault Falcon 7X",
    "Beechcraft King Air",
    "Boeing AH-64 Apache",
    "Bell UH-1 Iroquois (Huey)",
    "Eurofighter Typhoon",
    "Lockheed Martin F-22 Raptor",
    "Lockheed Martin F-35 Lightning II",
    "Boeing B-52 Stratofortress",
    "Northrop Grumman B-2 Spirit",
    "Boeing F/A-18 Super Hornet",
    "Airbus Eurocopter EC135",
    "Sikorsky UH-60 Black Hawk",
    "Boeing CH-47 Chinook",
    "Airbus A400M Atlas",
    "Lockheed C-5 Galaxy",
    "Boeing KC-135 Stratotanker",
    "Airbus KC-30 MRTT",
    "Antonov An-225 Mriya",
    "Tupolev Tu-160 Blackjack",
    "Boeing 707",
    "McDonnell Douglas DC-10",
    "Boeing C-17 Globemaster III",
    "Lockheed Martin C-130J Super Hercules",
    "Boeing E-3 Sentry (AWACS)",
    "Boeing E-4B Nightwatch",
    "Airbus A330 MRTT",
    "Boeing P-8 Poseidon",
    "Lockheed P-3 Orion",
    "Airbus A310 MRTT",
    "Boeing AH-6 Little Bird",


    ///pindah model///


"RMS Titanic",
"HMS Queen Elizabeth",
    "USS Enterprise (CV-6)",
    "USS Missouri (BB-63)",
    "HMS Victory",
    "HMS Bounty",
    "USS Constitution",
    "HMS Beagle",
    "SS Great Eastern",
    "USS Monitor",
    "HMS Endeavour",
    "USS Nautilus (SSN-571)",
    "HMS Hood",
    "USS Arizona (BB-39)",
    "HMS Dreadnought",
    "USS Nimitz (CVN-68)",
    "USS Iowa (BB-61)",
    "HMS Ark Royal",
    "USS John F. Kennedy (CV-67)",
    "RMS Lusitania",
    "HMS Repulse",
    "USS Yorktown (CV-10)",
    "HMS Warrior",
    "USS Hornet (CV-8)",
    "HMS Invincible",
    "USS Lexington (CV-16)",
    "RMS Queen Mary",
    "USS Constellation (CV-64)",
    "HMS Belfast",
    "USS New Jersey (BB-62)",
    "USS Enterprise (CVN-65)",
    "RMS Queen Elizabeth 2",
    "USS Wisconsin (BB-64)",
    "USS Gerald R. Ford (CVN-78)",
    "HMS Prince of Wales",
    "USS Midway (CV-41)",
    "HMS Illustrious",
    "USS Missouri (SSN-780)",
    "HMS Royal Oak",
    "USS Seawolf (SSN-21)",
    "RMS Carpathia",
    "HMS Vanguard",
    "USS Theodore Roosevelt (CVN-71)",
    "HMS Hood",
    "USS Gerald R. Ford (CVN-78)",


    ///pindah model///


"Falcon 9",
"Saturn V",
    "Space Shuttle",
    "Atlas V",
    "Delta IV",
    "Soyuz",
    "Falcon Heavy",
    "Blue Origin New Shepard",
    "Ariane 5",
    "Vega",
    "H-IIA",
    "Long March 5",
    "Proton",
    "GSLV Mk III",
    "Angara A5",
    "Zenit",
    "Electron",
    "Pegasus",
    "Antares",
    "Minotaur",
    "Titan II",
    "Atlas III",
    "Vulcan Centaur",
    "Starship",

      ];
  
  input.addEventListener("keypress", function (event) {
    if (event.key === "Enter") {
      event.preventDefault();
      document.getElementById("picit").click();
    }
  });
  
  function picit() {
    if (document.getElementById("input").value == "") {
      alert("Anda tidak memasukkan apapun!");

    } else {
      let x = document.getElementById("input").value;
      let y = Math.floor(Math.random() * 210);
      document.getElementById("name").innerHTML = x;
      document.getElementById("container").style.display = "none";
      document.getElementById("hasil").style.display = "block";
      document.getElementById("kendaraan").innerHTML = kendaraan [(0, y)];
  
      console.log(y);
    }
  }
  